import type { Metadata } from "next";
import { Cedarville_Cursive } from "next/font/google";
import "./globals.css";

const cedarvileCursive = Cedarville_Cursive({
  subsets: ["latin"],
  variable: "--font-cedarvile-cursive",
  display: "swap",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "My invitation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className={`${cedarvileCursive.variable}`}>
      <body>{children}</body>
    </html>
  );
}
